# Generated by Django 6.0.5 on 2026-05-17 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_brand_name_alter_category_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('deal', 'Deal Alert'), ('price_drop', 'Price Drop'), ('back_in_stock', 'Back in Stock'), ('order', 'Order Update'), ('promo', 'Promotion'), ('system', 'System')], default='system', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.URLField(blank=True, help_text='Optional link to product/order')),
                ('is_read', models.BooleanField(default=False)),
                ('toast_shown', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='shop_notifi_user_id_fcf7e5_idx')],
            },
        ),
    ]
