# Generated by Django 6.0.5 on 2026-05-17 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('shop', '0002_alter_brand_name_alter_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='cart.cartitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='shop.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'expires_at'], name='cart_stockr_product_c90f5f_idx')],
            },
        ),
    ]
